services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nora_db
      POSTGRES_USER: nora_user
      POSTGRES_PASSWORD: nora_pass
    ports:
      - "5430:5432" #Не "убиваем" СУБД Postgres, а занимает порт 5430
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  postgres_data: